### PR TITLE
Add initialVisibleMonth fn prop to DayPicker

### PR DESCRIPTION
**Pull request by amitava82**
Adds a new prop to DateRangePicker, SingleDatePicker, and DayPicker
that passes a fn to DayPicker. On the initial focus, that fn will be called
and set the initial month to the returned moment object.

solves issue #17

### CODE REVIEW

**Comment by StrikoMirko** [comment]
Hi, can this added feature be published to npm?
Im getting the latest npm react-dates but Im not getting this feature.
I presume this has not been published to npm yet.

Thank you.

**Comment by amitava82** [comment]
Hi @StrikoMirko , this is not published since I'm hoping it will eventually be updated in the main library soon. For now you can clone and build. I needed this urgently for my project.

**Comment by StrikoMirko** [comment]
Hi @amitava82 , thank you for the reply. I did as you said and tested it and it works like a charm.
The only thing is that our for our build process we need this in npm. Do you have any idea when this will be published?

Thank you.

**Comment by amitava82** [comment]
I have no clue!
Perhaps you  can clone this repo and publish to npm. Or put the built files in github repo and use that in` `package.json`

**Pull request merged**
